import type { ResolvedConfig } from "../types.js";

export const DEFAULT_CONFIG: ResolvedConfig = {
  enabled: true,
  setupComplete: false,
  scope: {
    mode: "domain-tagged",
    projectIdStrategy: "remote",
    includeSharedObservations: false,
    userScopeTags: ["source:pi", "harness:pi"],
    unscopedRecallBanks: [],
  },
  hindsight: { baseUrl: "http://localhost:8888", timeoutMs: 30_000 },
  agentUse: "coding",
  mentalModels: {
    inject: true,
    maxChars: 12_000,
    cacheTtlMs: 300_000,
  },
  banks: {
    project: { enabled: true, derive: "repo" },
    global: { enabled: false },
    user: { enabled: false },
  },
  recall: {
    enabled: true,
    budget: "mid",
    maxTokens: 800,
    userMaxTokens: 400,
    types: ["observation"],
    includeSourceFacts: false,
    maxSourceFactsTokens: 4096,
    contextTurns: 2,
    roles: ["user", "assistant"],
    maxQueryChars: 800,
    queryPreamble: "Pi coding task memory lookup.",
    projectQueryPreamble:
      "Project memory lookup for current repo architecture, tasks, bugs, decisions, and constraints.",
    globalQueryPreamble:
      "User memory lookup for durable user preferences, recurring workflows, coding habits, and cross-project context.",
    userQueryPreamble:
      "User memory lookup for durable user preferences, recurring workflows, coding habits, and cross-project context.",
    includeDateInQuery: false,
    includeRepoHintsInQuery: true,
    storeLastRecall: false,
    storeLastRecallFailures: false,
    lastRecallPath: ".pi/hindsight/last-recall.json",
    topK: 8,
    timeoutMs: 40_000,
    cacheTtlMs: 60_000,
    injectionMode: "context",
    injectionPosition: "append",
    includeFactsInDebug: false,
    preferObservations: true,
  },
  observations: {
    enabled: true,
    // Project-stable scope; {repoKey} remains a supported placeholder for legacy configs.
    scopes: [["harness:pi"], ["project:{projectId}"]],
  },
  globalRetain: {
    mode: "explicit-only",
  },
  userRetain: {
    mode: "explicit-only",
  },
  retain: {
    enabled: true,
    async: true,
    delivery: "immediate",
    updateMode: "append",
    content: {
      user: ["text"],
      assistant: ["text", "toolCall"],
      toolResult: ["error"],
    },
    toolFilter: {
      toolCall: {
        exclude: [
          "hindsight_retain",
          "hindsight_retain_global",
          "hindsight_delete_document",
          "hindsight_retain_receipts",
          "hindsight_route_memory",
          "hindsight_recall",
          "hindsight_reflect",
        ],
      },
      toolResult: {
        exclude: [
          "hindsight_retain",
          "hindsight_retain_global",
          "hindsight_delete_document",
          "hindsight_retain_receipts",
          "hindsight_route_memory",
          "hindsight_recall",
          "hindsight_reflect",
          "read",
          "grep",
          "find",
          "find_files",
          "ls",
        ],
      },
    },
    compactToolCalls: true,
    strip: { message: ["usage", "cost", "responseId"], topLevel: ["id", "parentId"] },
    redactSecrets: true,
    entities: [],
    queuePath: ".pi/hindsight/retain-queue.jsonl",
    flushIntervalMs: 0,
    periodicFlushMaxJobs: 1,
    periodicFlushTimeoutMs: 2_000,
    shutdownFlushMaxJobs: 10,
    shutdownFlushTimeoutMs: 2_000,
    postRetainReflect: false,
  },
  import: {
    mode: "curated",
    qualityProfile: "compatible",
    turnsPerDocument: 12,
    maxDocumentBytes: 80_000,
    includeBranches: "current-only",
    toolResults: "errors-only",
    toolResultSummaryMaxChars: 500,
    replaceExistingImportedDocs: true,
    manifestPath: ".pi/hindsight/import-manifest.json",
    checkpointPath: ".pi/hindsight/import-checkpoint.json",
    resume: true,
  },
  status: {
    style: "text",
    detail: "activity",
    maxLength: 24,
    showActivity: true,
  },
  notifications: {
    startup: true,
    recall: false,
    retain: false,
  },
};
